<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?php // we need to include Popper.js for dropdown menu items ?>
        <?= $this->headScript()
        //    ->prependFile('https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js')
        ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                    <span class="navbar-text text-light">MVC Skeleton</span>
                </a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?= $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav me-auto')
                    ?>
                    <?php $user = $this->lmcUserIdentity(); ?>
                    <?php if (!$user): ?>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Login in</a>
                                <div class="dropdown-menu p-1">
                                    <?php /** @var \LmcUser\Form\Login $loginForm */ ?>
                                    <?php $loginForm = $this->lmcUserLoginWidget(['render' => false])->getVariable('loginForm');?>
                                    <?php $loginForm->setAttribute('action',$this->url('lmcuser/login'))?>
                                    <?= $this->form()->openTag($loginForm);?>
                                    <div class="form-group mb-1">
                                        <?php $loginForm->get('identity')->setAttributes([
                                            'class' =>'form-control',
                                            'placeholder' => 'Email',
                                        ]);?>
                                        <?= $this->formElement($loginForm->get('identity'));?>
                                    </div>
                                    <div class="form-group mb-1">
                                        <?php $loginForm->get('credential')->setAttributes([
                                            'class'=> 'form-control',
                                            'placeholder' => 'Password',
                                        ]);?>
                                        <?= $this->formElement($loginForm->get('credential'));?>
                                    </div>
                                    <?= $this->formElement($loginForm->get('security'));?>
                                    <?php $loginForm->get('submit')->setAttribute('class', 'btn btn-primary');?>
                                    <?= $this->formElement($loginForm->get('submit'));?>
                                    <?= $this->form()->closeTag();?>                                </div>
                            </li>
                        </ul>
                    <?php else: ?>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a class="nav-link dropdown-toggle" role="button" href="#" data-bs-toggle="dropdown">Hi <?= $this->lmcUserDisplayName();?>!</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="<?= $this->url('lmcuser');?>">Profile</a></li>
                                    <li><a class="dropdown-item" href="<?= $this->url('lmcuser/logout');?>">Log out</a></li>
                                </ul>
                            </li>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->navigation('navigation')
                ->breadcrumbs()
                ->setMinDepth(0)
                ->setPartial('partial/breadcrumbs')
            ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.bundle.min.js')) ?>
    </body>
</html>
