<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">MVC Skeleton
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?= $this->navigation('navigation')
                            ->menu()
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->setUlClass('nav navbar-nav');
                    ?>
                    <?php $user = $this->lmcUserIdentity(); ?>
                    <?php if (!$user): ?>
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a data-toggle="dropdown" href="#">Log in</a>
                                <div class="dropdown-menu dropdown-menu-right p-1">
                                    <?php /** @var \LmcUser\Form\Login $loginForm */?>
                                    <?php $loginForm = $this->lmcUserLoginWidget(['render' => false])->getVariable('loginForm');?>
                                    <?= $this->form()->openTag($loginForm);?>
                                    <div class="form-group">
                                        <?php $loginForm->get('identity')->setAttributes([
                                                'class' =>'form-control',
                                                'placeholder' => 'Email',
                                            ]);?>
                                        <?= $this->formElement($loginForm->get('identity'));?>
                                    </div>
                                    <div class="form-group">
                                        <?php $loginForm->get('credential')->setAttributes([
                                                'class'=> 'form-control',
                                                'placeholder' => 'Password',
                                            ]);?>
                                        <?= $this->formElement($loginForm->get('credential'));?>
                                    </div>
                                    <?= $this->formElement($loginForm->get('security'));?>
                                    <?php $loginForm->get('submit')->setAttribute('class', 'btn btn-primary');?>
                                    <?= $this->formElement($loginForm->get('submit'));?>
                                    <?= $this->form()->closeTag();?>
                                </div>
                            </li>
                        </ul>
                    <?php else: ?>
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a data-toggle="dropdown" href="#">Hi <?= $this->lmcUserDisplayName();?>!</a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="<?= $this->url('lmcuser');?>">Profile</a>
                                    <a class="dropdown-item" href="<?= $this->url('lmcuser/logout');?>">Log out</a>
                                </div>
                            </li>
                        </ul>
                    <?php endif;?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php // add the following line: ?>
            <?= $this->navigation('navigation')
                ->breadcrumbs()
                ->setMinDepth(0)
                ->setPartial('partial/breadcrumb');
            ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
